
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    port: 6379
    host: 127.0.0.1
    password: ''
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/marketdb?characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
    password: 1234

token:
  access_expiration_time: 86400000
  #  1day
  refresh_expiration_time: 864000000
  secret: user_token

# get from application-dev.yml
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    s3:
      bucket:
    region:
      static:
    stack:
      auto: false