
spring:
  data:
    web:
      pageable:
        one-indexed-parameters: true
  datasource:
    url: ENC(dsZ3coQelNu9GjYT8mbN+fv7Ucrt2xgwsCjQH3a+orI=)
    driver-class-name: org.h2.Driver
    username: ENC(V1/UzJx6/uvDS1xTyQSUG8CKnRfTuV9S2aeaxrjCLhs=)
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

jasypt:
  encryptor:
    bean: jasyptEncryptor